### ISSUE TITLE
[RFE] Add option to output results in machine-readable format

### ISSUE THREAD

**Issue by dustinblack** [jtaleric/k8s-netperf#35]
It would be nice to get all of the output delivered in JSON or YAML or something else better machine-readable than CSV.

**Comment by dustinblack** [comment]
Since you are already creating a document for Opensearch, I imagine it's trivial to provide an option to output the JSON directly.

**Comment by jtaleric** [comment]
>  better machine-readable than CSV. 

Curious why CSV doesn't suffice? Can you elaborate why -- seems easy to ingest in many modern tools.

**Comment by jtaleric** [comment]
Is the ask to *just* display json/yaml to stdout?

**Comment by jtaleric** [comment]
Checking in on this, haven't heard back...
